### ISSUE TITLE
It seems that there is no part in the project to verify the JWT signature?

### ISSUE THREAD

**Issue by BoysheO** [alexalok/AppStoreServerNotificationsV2#7]
It seems that there is no part in the project to verify the JWT signature?I am currently learning how to verify the in-app purchase callback for ASSNv2.I find no way to verify JWT from apple

**Comment by alexalok** [comment]
As you have correctly pointed out, the library doesn't support validating the received notifications: https://github.com/alexalok/AppStoreServerNotificationsV2/blob/main/AppStoreServerNotificationsV2%2FConverters%2FJWSTransactionDecodedPayloadConverter.cs#L17

**Comment by BoysheO** [comment]
Hello,I have found out the way to verify JWT signature from apple.See https://stackoverflow.com/questions/79158696/how-to-verify-jws-in-dotnet/79253651#79253651.Thank you~You may like to update your solution
